version: '3'  # Docker Compose specification version

services:  # Define services
  nats:  # NATS service
    image: nats:latest  # Use the latest NATS image
    ports:
      - "4222:4222"  # Port for client connections
      - "8222:8222"  # Port for HTTP monitoring
    command: ["-js"]  # Start NATS with JetStream enabled
    volumes:
      - nats-data:/data  # Add a volume for data storage
    restart: unless-stopped  # Restart policy

volumes:
  nats-data:  # Define a volume for NATS data
